# Macro de visualización inicial
/run/initialize

/vis/open OGL 900x700-0+0
/vis/viewer/set/background white
/vis/drawVolume
/vis/viewer/set/viewpointThetaPhi 70 30
/vis/viewer/set/autoRefresh true
/vis/scene/add/axes 0 0 0 10 cm

# Ver trayectorias
/tracking/storeTrajectory 1
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set e- blue
/vis/modeling/trajectories/drawByParticleID-0/set e+ red
/vis/scene/endOfEventAction accumulate 50

# Generamos pocos eventos para ver las líneas
/run/beamOn 20
